name: Continuous Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/coderman.ru/data/www/leadest.coderman.ru
            git pull
            composer install
            php artisan config:cache
            php artisan migrate
            cd ..
            chown -R coderman.ru:coderman.ru leadest.coderman.ru/
